### ISSUE TITLE
Stuck on "velocity_limit service is not ready" when scenario contains a pedestrian

### ISSUE THREAD

**Issue by WilliamFlinchbaugh** [autowarefoundation/AWSIM-Labs#124]
I was trying to create a simple scenario with an ego vehicle and a pedestrian crossing the street. However, it seems like whenever there's a pedestrian in the scenario, it stalls on `[simulation.concealer_user]: /api/autoware/set/velocity_limit service is not ready.` after launching. 

All I did was copy sample_awsim.yaml scenario which works perfectly and add a pedestrian.The issue seems to not be with defining the pedestrian scenario object, but with the teleport and routing action within the storyboard as well as the action in the story. It seems to work fine with just the pedestrian defined under ScenarioObject, and I don't get any parsing errors or anything.

I attached the scenario yaml file I'm using. If anyone has an example of pedestrian movement in a scenario, that would be incredibly helpful.

[pedestrian_scenario.txt](https://github.com/user-attachments/files/16367215/pedestrian_scenario.txt)

The only parts I added to the sample_awsim.yaml scenario were the following:

- Under ScenarioObject: 
```
- name: Pedestrian0
    Pedestrian:
      name: Pedestrian
      mass: 60
      model: ''
      pedestrianCategory: pedestrian
      BoundingBox:
        Center:
          x: 0
          y: 0
          z: 1
        Dimensions:
          length: 0.8
          width: 0.8
          height: 2
      Properties:
        Property: []
    ObjectController:
      Controller:
        name: ''
        Properties:
          Property: []
```
              
- Under Storyboard/Init/Actions/Private:
```
- entityRef: Pedestrian0
    PrivateAction:
      - TeleportAction:
          Position:
            WorldPosition:
              x: 81615.148
              y: 50042.0498
              z: 1
              h: -1.3947
              p: -0.0
              r: 0
      - RoutingAction:
          AcquirePositionAction:
            Position:
              WorldPosition:
                x: 81622.8167
                y: 50003.3951
                z: 0.15
                h: -1.4096
                p: -0.0
                r: 0
```

- Under Story/Act/ManeuverGroup/Maneuver/Event:
```
- name: ''
    priority: parallel
    StartTrigger:
      ConditionGroup:
        - Condition:
            - name: ''
              delay: 0
              conditionEdge: none
              ByValueCondition:
                SimulationTimeCondition:
                  value: 180
                  rule: greaterThan
        - Condition:
            - name: ''
              delay: 0
              conditionEdge: none
              ByEntityCondition:
                TriggeringEntities:
                  triggeringEntitiesRule: any
                  EntityRef:
                    - entityRef: ego
                EntityCondition:
                  CollisionCondition:
                    EntityRef:
                      entityRef: Pedestrian0
    Action:
      - name: ''
        UserDefinedAction:
          CustomCommandAction:
            type: exitFailure
```
