### ISSUE TITLE
Turn on the side lidars

### ISSUE THREAD

**Issue by xmfcx** [autowarefoundation/AWSIM-Labs#51]
In the AWSIM Autoware configuration and in the simulation, there are 2 side lidars. With the lidar on top, there are 3 VLP16s on the vehicle.

In the old HDRP, due to performance issues side lidars were turned off.

Let's turn them back on.

Also @brkay54 tested the side lidars and will share some problems they have.

Probably if we just move(translate) them slightly to the sides, the problems will be fixed.

**Comment by brkay54** [comment]
**The current left and right lidar output is shown here. My concerns are:**
- side lidars are not symmetrical
- they can not see the front of the vehicle
![3-2](https://github.com/autowarefoundation/AWSIM/assets/45468306/e7a90ae8-e969-4edb-ba9a-948f9d826753)

**We made some draft changes, the points on the vehicle were increased but the side lidars can see the front. It is just a draft setup we can improve it.**
![3-1](https://github.com/autowarefoundation/AWSIM/assets/45468306/10786123-4d68-4267-8d1b-10e6be9b4d8a)

**Sensor positions before change:**
```
  velodyne_left_base_link:
    x: 0.0
    y: 0.56362
    z: -0.30555
    roll: -0.02
    pitch: 0.71
    yaw: 1.575
  velodyne_right_base_link:
    x: 0.0
    y: -0.56362
    z: -0.30555
    roll: -0.01
    pitch: 0.71
    yaw: -1.580
```

**Sensor positions after change:**
```
  velodyne_left_base_link:
    x: 0.0
    y: 0.6
    z: -0.30555
    roll: -0.020000007151
    pitch: 0.70999994
    yaw: 1.5749851
  velodyne_right_base_link:
    x: 0.0
    y: -0.6
    z: -0.30555
    roll: -0.020000007151
    pitch: 0.70999994
    yaw: -1.5749851
```
