### ISSUE TITLE
Add feature to spawn NPC from RVIZ

### ISSUE THREAD

**Issue by mitsudome-r** [autowarefoundation/AWSIM-Labs#65]
# Description
We could add a feature to AWSIM to receive a dummy perception message from RVIZ to spawn an NPC vehicle at user's demands just like in this tutorial: https://autowarefoundation.github.io/autoware-documentation/main/tutorials/ad-hoc-simulation/planning-simulation/#placing-dummy-objects

**Comment by SujayAmberkar** [comment]
I'm getting this message when I listen to the /simulation/dummy_perception_publisher/object_info,
here the position is around 81000 & 49000 for x and y whenever I create a dummy NPC in rviz. 
1. Should I be using this position?
2. Should it be converted?

```
initial_state:
  pose_covariance:
    pose:
      position:
        x: 81383.5859375
        y: 49919.77734375
        z: 0.0
      orientation:
        x: 0.0
        y: 0.0
        z: 0.2974268081526713
        w: 0.95474462229023
 
```

**Comment by mozhoku** [comment]
@SujayAmberkar you can check out this. 

https://github.com/autowarefoundation/AWSIM-Labs/blob/a99f67e1261df08d405de16883d8e000a1140485/Assets/AWSIM/Scripts/Sensors/Gnss/GnssSensor.cs#L73

I'm not sure if it does anything else with the coordinate values.

**Comment by xmfcx** [comment]
Message should be added as a custom message:
- https://github.com/autowarefoundation/autoware.universe/tree/36b0b2bde9f49c2d1700266fcb50afff12d618b9/simulator/dummy_perception_publisher/msg

**Comment by SujayAmberkar** [comment]
@mozhoku I want to create a new custom message but I'm unsure if it'll cause any problems. And you're working on an issue of replacing older messages with new ones so I wanted to know what I should take care of while creating a new custom message. By reading that issue I could only understand that it's something related to the change of names.

**Comment by mozhoku** [comment]
@SujayAmberkar if you are adding a new custom message it shouldn't affect anything. I will be replacing the current message types used by the simulation so that it can communicate with the main autoware_universe branch after the msg changes. 
For example: `autoware_auto_perception_msgs` => `autoware_perception_msg`.

**Comment by xmfcx** [comment]
@SujayAmberkar do you have any updates on this feature? We would like to speed up this feature's development, it is important for the planning team.

**Comment by SujayAmberkar** [comment]
@xmfcx Hello, extremely sorry for the delay. I'll finish this as soon as possible. I'm facing a problem here. I cannot access the position inside the message after adding a custom message in Unity and writing the following code. 
```
initial_state:
  pose_covariance:
    pose:
      position:
        x: 81383.5859375
        y: 49919.77734375
        z: 0.0
      orientation:
        x: 0.0
        y: 0.0
        z: 0.2974268081526713
        w: 0.95474462229023
 ```
```cs
public class RVIZNPCSpawner : MonoBehaviour
    {
        [SerializeField] string NPCSpawnerTopic = "/simulation/dummy_perception_publisher/object_info";

        // Subscriber
        ISubscription<dummy_perception_publisher.msg.Object> NPCSpawnerSubscriber;

        void Start()
        {
            // Define default QoS settings
            QoSSettings qosSettings = new QoSSettings();
            
            // Initialize the ROS2 node and create the subscription
            NPCSpawnerSubscriber = SimulatorROS2Node.CreateSubscription<dummy_perception_publisher.msg.Object>(
                NPCSpawnerTopic, NPCSpawnerCallback, qosSettings.GetQoSProfile());
        }

        /// <summary>
        /// Callback method to handle incoming messages
        /// </summary>
        /// <param name="msg">Received Object message</param>
        void NPCSpawnerCallback(dummy_perception_publisher.msg.Object msg)
        {
            Debug.Log(msg.initial_state.pose_covariance.pose.position.x);        }

        void OnDestroy()
        {
            // Clean up the subscription when the GameObject is destroyed
            SimulatorROS2Node.RemoveSubscription<dummy_perception_publisher.msg.Object>(NPCSpawnerSubscriber);
        }
    }
```
I get this error,
error CS1061: 'Object' does not contain a definition for 'initial_state' and no accessible extension method 'initial_state' accepting a first argument of type 'Object' could be found (are you missing a using directive or an assembly reference?)
